### ISSUE TITLE
Java version test is still looking for Java 7

### ISSUE THREAD

**Issue by SteveFreeman** [WASdev/tool.lars#181] opened 2019-10-01 17:07 UTC

**Comment by BillyD73** [comment] 2019-10-02 13:35
Hi @SteveFreeman, would it please be possible for you to provide some more information (logs, does the error occur during building lars or running it, which version of Java you are using etc) so that I can get this fixed ASAP?

**Comment by SteveFreeman** [comment] 2019-10-02 14:04
This happens in the automated testing (during the build). The test report indicates this. I'm attaching the content.

[buildreport.zip](https://github.com/WASdev/tool.lars/files/3681457/buildreport.zip)

**Comment by SteveFreeman** [comment] 2019-10-02 14:05
sorry, closed by mistake

**Comment by SteveFreeman** [comment] 2019-10-02 15:29
Also: when building with Java 8, the larsServer.zip is not created in the server/build/distributions folder

**Comment by BillyD73** [comment] 2019-10-03 13:33
Hi @SteveFreeman - this problem is caused by the java7Home variable being set within the gradle.properties file. This is an optional variable to test on Java 7 as well as the Java you are using. Work is underway to update this variable to Java 8, as Java 7 is no longer supported. For the time being removing it from the config will fix this problem.

**Comment by SteveFreeman** [comment] 2019-10-03 15:49
Yes, removing java7Home fixes the problem.  Can you update the doc to state this, please?

**Comment by BillyD73** [comment] 2019-10-04 10:21
The doc has been updated to reflect this

**Comment by SteveFreeman** [comment] 2019-10-04 12:55
I'm not seeing any changes or pull requests related to this.  Can you point me to the updated doc, please?

**Comment by BillyD73** [comment] 2019-10-07 11:17
Hi Steve - the updated doc is here: https://github.com/WASdev/tool.lars/wiki/Downloading-LARS

We recently made the decision to move our documentation from the readmes to the Wiki.

**Comment by SteveFreeman** [comment] 2019-10-07 13:36
Thanks Billy.  You might need a link from the readmes to the wiki in this case.  Also, I would rename that page to "Downloading and Building LARS"

**Comment by BillyD73** [comment] 2019-11-22 09:53
This has been fixed with the [2.0.1 release](https://github.com/WASdev/tool.lars/releases/tag/v2.0.1)

**Closed as completed by BillyD73** 2019-11-22 09:53 UTC
